trigger:
  - master
  - v5.0
pr:
  - master
  - v5.0

resources:
  - repo: self
    clean: true
    fetchDepth: 1

jobs:
  - job: ps3
    displayName: PowerShell 3
    continueOnError: false
    pool:
      name: Default
      demands:
        - ps3
    workspace:
      clean: all
    timeoutInMinutes: 3
    steps:
      - powershell: |
          $global:PesterDebugPreference_ShowFullErrors = $true
          $errorActionPreference = 'stop'
          Set-StrictMode -Version Latest
          $r = Get-ChildItem *.ts.ps1 -Recurse | foreach { & $_.FullName -PassThru }
          Write-Host "reporting result"
          $failed = $r | Where-Object { $_.Failed -gt 0 }
          $failed | Out-String
          "Failed is: $($null -eq $failed )"
          if ([bool]$failed) { exit 1 }
          Import-Module .\Pester.psd1
          Invoke-Pester -ExcludeTag VersionChecks, StyleRules, Help -ExcludePath -ExcludePath '*/demo/*', '*/examples/*', '*/Gherkin*' -CI | Out-Null
